#!/bin/bash

dir1=~/Documents/Exams/

# Topics with which to sort the pdfs
# Do not forget to update the local_topics variable inside the
# function process_file
#topics=(physics articles books notes notes_personal mathematics)

# Delete the existing links to start from scratch
#for topic in ${topics[@]}; do
#    rm -r /home/simao/documents/$topic
#    mkdir /home/simao/documents/$topic
#done


# Use exiftool on the given filename to find all the metadata tags
# that it contains. Then, make links to certain folders according 
# to those tags
function process_file(){
	#    local_topics=(physics articles books notes notes_personal mathematics)
	#    num_topics=${#local_topics[@]}
	#    subject=$(exiftool -Subject "$1" 2> /dev/null);
	cadeira=$(basename "$PWD")
	ano_leti=$(./get_ano.py $(find -type f -iname \*.pdf -print)))

	if [ "$subject" != "" ]; then 
		for ((i = 0; i < $num_topics; i++)); do
			topic=$(echo $subject | grep -w ${local_topics[$i]})
			if [ "$topic" != "" ]; then
				ln -s "$1" /home/simao/documents/${local_topics[$i]}
			fi
		done
	fi
}
export -f process_file

find $dir1 -type f -iname \*.pdf -print0 | xargs -I % -P 4 -0 bash -c "process_file \"%\""
